# Generated by Django 5.2.1 on 2025-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('furniture', 'Furniture')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
